services:
  aurora-api:
    image: aurora-api:latest
    container_name: aurora-api
    build: .
    ports:
      - ${PORT:-8000}:8000
    environment:
      - IGNORE_CORS=true
    env_file: .env
    restart: unless-stopped
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ${MEDIA_PATH:-./media}:/app/media
