- name: Deploy {{ ENV_NAME }} aurora-api
  hosts: all
  become: false
  vars:
    project_dir: "~/deploy/{{ ENV_NAME }}-aurora-api"

  tasks:
    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ ENV_NAME }}/{{ item }}"
        dest: "{{ project_dir }}/{{ item }}"
        mode: "0755"
        backup: false
        remote_src: false
      loop:
        - compose.yaml

    - name: Pull new frontend image
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
      register: out
      changed_when: out.rc != 0

    # https://github.com/tortoise/aerich/issues/384
    - name: Run migrations
      ansible.builtin.command:
        cmd: docker compose run --rm aurora-api timeout 25 aerich upgrade
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
      timeout: 30
      register: out
      changed_when: out.rc != 0
      ignore_errors: true

    - name: Deploy new image
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
        PORT: "{{ PORT }}"
        IGNORE_CORS: "{{ IGNORE_CORS }}"
        OW_API_KEY: "{{ OW_API_KEY }}"
        ALLOWED_ORIGINS: "{{ ALLOWED_ORIGINS }}"
      register: out
      changed_when: out.rc != 0
